def load_raw_data(path):
    ...

def clean_data(df):
    # sélection de colonnes, gestion des NA, etc.
    ...

def split_train_test(df, test_size=0.2, random_state=42):
    ...

def save_processed(train_df, test_df, train_path, test_path):
    ...
